### ISSUE TITLE
Linux version compiled with wrong source

### ISSUE THREAD

**Issue by Gnome16** [eriklins/Pascal-Bindings-For-SimpleBLE-Library#14]
The Linux version only works if these lines are commented out:
```
  TSimpleBleService = record
    Uuid: TSimpleBleUuid;
    // DataLength: NativeUInt;
    // Data: array[0..27-1] of Byte;
    CharacteristicCount: NativeUInt;
    Characteristics: array[0..SIMPLEBLE_CHARACTERISTIC_MAX_COUNT-1] of TSimpleBleCharacteristic;
  end;
```
Because of this, I think, Linux InsideBlue 0.6 crashes when connecting. IB 0.6 also returns the wrong MTU on some devices (Linux version says MTU is 3, Windows version says it's 160), possibly the same problem.

**Comment by eriklins** [comment]
Hum... I maybe put an older version of the SimpleBLE library into the ZIP archive for Linux. The latest 0.6 release of SimpleBLE got those two variables added and should hence work. Let me check.

**Comment by eriklins** [comment]
I updated the v0.6 Linux release package of InsideBlue with the latest release of SimpleBLE library.

**Comment by eriklins** [comment]
Regarding the wrong MTU, I cannot replicated this. An MTU of 3 looks weird. Since SimpleBLE doesn't return the proper MTU size in simpleble_peripheral_mtu() but returns the attribute data length instead (see issue #212 in SimpleBLE), I add up 3 to get the proper MTU in InsideBlue. An MTU of 3 in InsideBlue would hence mean it got zero back from simpleble_peripheral_mtu().

The MTU size always starts with 23 when engaging a BLE connection (due to BT specification) and can subsequently be negotiated for larger values between the peers. InsideBlue do update the MTU value in the device form during an active connection regularly. Depending on what is set for max. MTU on the client side (Windows or Linux PC), the actual MTU values being agreed on by the peers might vary and hence be different on different PCs and OS's. Older PC's might not even support data length extension (DLE) and hence would eventually be limited to 23.

**Comment by Gnome16** [comment]
That didn't work, but there seems to be more wrong with SimpleBLE in Linux than just the MTU. As well as reporting an MTU size of 3 it also reports that the device has zero services. The Windows version seems to work OK though (in Win64 of course as the Win32 build also doesn't work). InsideBlue also gives a divide by zero error, but that's probably caused by SimpleBLE not working.

It's a pity Kevin refuses to release official SimpleBLE DLL and SO files as that would remove any doubts about the Linux builds themselves. (Your builds still need PATCHELF run on them to remove the ERIK run path).

**Comment by eriklins** [comment]
The precompiled Linux release of InsideBlue works here on a native Linux 64 Ubuntu machine and shows proper GATT table and MTU size for various devices. An empty GATT table (zero services) might be due a device requiring pairing and not having been paired prior to connecting from InsideBlue.
Also no need to run patchelf here since -R ./ was set when building InsideBlue on Linux.

**Comment by Gnome16** [comment]
For the device that fails I always get MTU zero and ServiceCount zero in my test program, regardless of whether the device is paired or not.

If it's a problem with SimpleBLE itself rather than the Pascal bindings (which I suspect is the case) it won't get fixed until one of the Rust/Python/C++ users runs into a device with the same issue. Since Kevin doesn't distribute any binaries, not even executables of the example programs, there is no way for me to show him the problem in a manner that he will accept.

**Comment by eriklins** [comment]
Have you tried compiling the sample applications with the shell script included in /utils...? With `./build_lib.sh -c -e simpleble` it builds all examples into `/SimpleBLE/build_simpleble_examples/bin`.

**Comment by Gnome16** [comment]
Thank you! That was easy. Is there a similar command to build the SO files? I can only see library object files in the build_simpleble folder.
I found another device where the services aren't picked up properly, even in the original example_connect program.

**Comment by eriklins** [comment]
You can build the shared libraries with `./build_lib.sh -c -s simpleble`. -c does a clean before building, hence optional.
