### ISSUE TITLE
size_t

### ISSUE THREAD

**Issue by Alexey-T** [eriklins/Pascal-Bindings-For-SimpleBLE-Library#2]
```
type
  {$IFDEF UNIX}
  size_t = csize_t;
  {$ENDIF}
```
looks bad, because you define global type size_t when SimpleBle unit is used. can you avoid size_t by replacing it with LongInt, or SizeInt, or Int64?

**Comment by eriklins** [comment]
Hi Alexey, thanks for the comment (and the other comments). I wasn't sure about what data type use instead of size_t. The original C/C++ lib used size_t, which - from my understanding - is architecture dependent, hence could be either 32 bit or 64 bit. I was reluctant to use some fixed sized data type since this could make records composed of size_t types no longer match the original C/C++ structures. Happy for any suggestion on this.

**Comment by Alexey-T** [comment]
> which - from my understanding - is architecture dependent, hence could be either 32 bit or 64 bit.

then it's NativeInt !

**Comment by Alexey-T** [comment]
or NativeUInt

**Comment by eriklins** [comment]
Fixed with commit 087cbea4e23d1d6fb673ddddf305e1a343c4ca1d
